### ISSUE TITLE
python3 support?

### ISSUE THREAD

**Issue by psifertex** [immunityinc/libptrace#1]
Given the imminent sunsetting of 2.7, any plans for 3.x compatibility? 

Edit: After reading the full readme the lack of 3.x makes more sense since this hasn't been under active development for many years. I'd imagine the answer is "it's open source, do it yourself", but figure I'll at least leave the issue open for now since it's a reasonable request.

**Comment by rhuizer** [comment]
Definitely something I still want to do, but the best approach is still up in the air.

I haven't investigated how different the Python 3.x C API is yet. But what I see the following options:

1. If the API is sufficiently close, a quick adaption of the existing code should be possible.
2. A second version could be written and maintained (undesirable; worst option).
3. Write some middle layer or do the bindings in Boost.Python or so.
4. Use SWIG or investigate alternatives.

If 1. is true then I think Python 3.x support could make it into the full 1.0.0 release still. I don't know if it is however.

Ideally at some point I'd like to get around to 4, but this will take time, and for now the best choice of framework is still up in the air. If anyone has suggestions to alternatives for SWIG I'm all ears.

Update: relevant link for later perusal http://python3porting.com/cextensions.html

**Comment by rhuizer** [comment]
This turned out to be relatively simple to wrap up during my night off.

It turned out that 1. was indeed the case, and the differences between the Python 2 and 3 C API are minimal. I haven't updated the example scripts yet, but for the rest this seems to be about it.

As such I've added _**completely untested**_ support for Python 3.7 (not 3.8 yet) on the `devel`  branch: https://github.com/immunityinc/libptrace/tree/devel

By completely untested I mean I ensured it built, and the Python 2.7 and 3.7 modules seemed to load.

Let me know if you do some testing?

**Comment by psifertex** [comment]
Awesome! I don't have an immediate need for it, I was just originally surprised by the 2.x requirement and figured filing an issue wouldn't hurt since others would likely have the same question. 

That said, I'll try to get some time to test it out shortly. Thanks for the very quick update.
